name: Golang-Pipeline
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4
      - name: Install Linting Tools
        run: |
          go install github
      - name: Run Linters
        run: golangci-lint run --out-format=colored-line-number
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: go test ./...
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag image
        run: |
          docker build -t 12-sprint-go-workflow .
          docker tag 12-sprint-go-workflow ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:v1
      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:v1
      - name: Debug Docker login credentials
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
