name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Linters
        run: |
          golangci-lint run
        
      - name: Run Unit Tests
        run: |
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag image
        run: |
          docker build -t 12-sprint-go-workflow .
          docker tag 12-sprint-go-workflow ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:v1
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:v1
