name: golang-pipeline
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
    - uses: actions/checkout@v4
    - name: Run Linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.1
        $(go env GOPATH)/bin/golangci-lint run

  test:
    needs: lint
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
    - uses: actions/checkout@v4
    - name: Run Unit Tests
      run: go test ./...
 deploy:
  if: github.event_name == 'push' && github.ref_type == 'tag'
  runs-on: ubuntu-latest
  needs: test
  steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:${{github.ref_name}}
