name: Golang-Pipeline

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-cache: false
          install-mode: binary

  test:
    needs: lint
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag image
        run: |
          docker build -t 12-sprint-go-workflow .
          docker tag 12-sprint-go-workflow ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:v1
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:v1
