name: golang-pipeline
on: push
   
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go environment
        run: echo "GOPATH=$HOME/go" >> $GITHUB_ENV

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Add GOPATH to PATH
        run: echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Run Linters
        run: |
          golangci-lint run
        
      - name: Run Unit Tests
        run: |
          go test ./...


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag image
        run: |
          docker build -t 12-sprint-go-workflow .
          docker tag 12-sprint-go-workflow ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:${{ github.ref_name }}
      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/12-sprint-go-workflow:${{ github.ref_name }}

